# Generated by Django 3.1.4 on 2020-12-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='nisargtrivedi054@gmail.com', max_length=100),
        ),
    ]
